spring.application.name=mangoDiyalo
server.port = 8081
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mango_diyalo}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB

application.security.jwt.secret-key=${JWT_SECRET:fallback_mango_key_diyalo_0_0_0}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
